extends: default

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
    indent-sequences: consistent
  trailing-spaces: disable
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
